apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-devops-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcp
  template:
    metadata:
      labels:
        app: gcp
    spec:
      containers:
      - name: gcp-devops-deployment
        image: gcr.io/geometric-shine-412917/gcpdevops:latest
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"